### ISSUE TITLE
Allow multiple demands to be assigned to a single junction

### ISSUE THREAD

**Issue by csweetapple** [smart-data-models/dataModel.WaterDistributionManagementEPANET#10]
In EPANET, multiple demands (consisting of a base demand and, optionally, a pattern and category) can be applied to a single junction. The current `Junction` entity only allows one set of demand information (under `demandCategory`) to be assigned to a junction (unless it is possible to assign multiple instances of the same property to an entity?).

This may be resolved when a `Simulation` entity is created, if the handling of demands and patterns is altered for this.

**Comment by eladsal** [comment]
@csweetapple I thought it was possible to have a number of `demandCategory` entries. In the example there is only one though:
https://github.com/smart-data-models/dataModel.WaterNetworkManagement/blob/master/Junction/examples/example-normalized-ld.jsonld

**Comment by csweetapple** [comment]
I think it may be possible with the new multi-attribute NGSI-LD property that's been mentioned in the IoT data model discussions? I'm not sure how this would be implemented though or if anything in the schema would need to be changed for this to be used.

**Comment by bobeal** [comment]
> I think it may be possible with the new multi-attribute NGSI-LD property that's been mentioned in the IoT data model discussions? I'm not sure how this would be implemented though or if anything in the schema would need to be changed for this to be used.

@csweetapple yes, you're right, this is possible with the new multi-attribute support in the NGSI-LD API.

The `demandCategory` would then look like:

```
"demandCategory": [
    {
        "type": "Property",
        "value": "agriculture demand",
        "datasetId": "urn:ngsi-ld:Dataset:XXX",
        "baseDemand": {
            "type": "Property",
            "value": "1.763868462",
            "unitCode": "MQS"
        },
        "demandPattern": {
            "type": "Relationship",
            "object": "urn:ngsi-ld:Pattern:fbcb5fc8-8ca3-4533"
    },
    {
        "type": "Property",
        "value": "another demand",
        "datasetId": "urn:ngsi-ld:Dataset:YYY",
        "baseDemand": {
            "type": "Property",
            "value": "2.4324238462",
            "unitCode": "MQS"
        },
        "demandPattern": {
            "type": "Relationship",
            "object": "urn:ngsi-ld:Pattern:aebbc6gc4-8ca3-4533"
    },
    ...
    ]
```

@AHABID any idea on implications on the associated schema?

**Comment by AHABID** [comment]
Yes.
ETSI's Schemas NGSI-LD (https://forge.etsi.org/rep/NGSI-LD/NGSI-LD/tree/master/schema) support the multiattribute, and we have may be to reference them instead of creating the schema again.

**Comment by albertoabellagarcia** [comment]
Answered, reopen if necessary
