### ISSUE TITLE
Current values of elements - Tank level

### ISSUE THREAD

**Issue by JuanAIMEN** [smart-data-models/dataModel.WaterDistributionManagementEPANET#14]
Where are the current values of an element inserted? I am checking the Tank data model and I want to include the current Level value. Currently, there are 3 level values (init, min and max) that help to describe the tank but I need to include the current level value measured by a level sensor. Where should I include it?
Something similar with the Pipe. If I want to associate pressure, flow and noise current values to a pipe, where should I include them?
Sorry if this is not the correct place to ask these questions.

**Comment by csweetapple** [comment]
The current values are not included at present. For the tank, however, it might be argued that the initial level (which relates to how the simulation is set up) should be the current level - and similar for initial quality where this is a property of a link or node.

**Comment by JuanAIMEN** [comment]
Ok, thank you! The name initLevel is a bit confusing if it corresponds to the current level.
 So will the measured values for a pipe (pressure, flow...) be included in the future?

**Comment by csweetapple** [comment]
> 
> 
> Ok, thank you! The name initLevel is a bit confusing if it corresponds to the current level.

I agree.... The name `initLevel` came from the properties used in EPANET to describe a tank and refers to the level applied at the start of a simulation. Thinking aloud, perhaps this is something that could be changed in a future iteration now that we are considering how the data model can be used more widely (i.e. not just to describe an EPANET model). This might not be practical though, depending on how the EPANET simulations are being used - e.g. if we were interested in simulating a historical or hypothetical scenario, the initial tank level applied in the simulation would not be the same as the current tank level, and we would still need a way of storing the initial level that was used.


> So will the measured values for a pipe (pressure, flow...) be included in the future?

Yes - although precisely how is still to be agreed. The measurements will be provided by a 'Device' (for which there is a separate data model), so I expect each property (pressure, flow etc.) for a network component will have a value and an `observedBy` relationship to a Device.

**Comment by albertoabellagarcia** [comment]
Although it makes all sense to have the properties into a related device it can also exist directly in an infrastructure element. There can exist use cases in which there is a need for having directly (reduction in the amount and complexity of queries, etc). It already happened on some other domains.

**Comment by albertoabellagarcia** [comment]
No further discussion, closing PR. Reopen if needed.
