### ISSUE TITLE
Flow property should be added

### ISSUE THREAD

**Issue by albertoabellagarcia** [smart-data-models/dataModel.WaterDistributionManagementEPANET#17]
The flow should be added as a property of the entity pipe. it is also necessary to determine how to set the direction of the flow.

**Comment by csweetapple** [comment]
I've started making some suggesions for how measured values (including flow) might be added to network components in https://github.com/smart-data-models/dataModel.WaterNetworkManagement/pull/16

In EPANET, which we should be consistent with, flow is measured from the `startsAt` to `endsAt` node (so can be positive or negative). Note also that the direction of flow within a pipe may be variable (as determined by the sign).

**Comment by albertoabellagarcia** [comment]
I understand this issue is on progress depending on #16.
