### ISSUE TITLE
initialquality has to be added to spec

### ISSUE THREAD

**Issue by albertoabellagarcia** [smart-data-models/dataModel.WaterDistributionManagementEPANET#18]
initialQuality does no appear in the spec.md. it has t be documented.
bulkReactionCofficient is also missing.

**Comment by csweetapple** [comment]
Is this for the Tank?
`bulkReactionCoefficient` and `initialQuality` were added to the Tank spec in PR #19.

**Comment by albertoabellagarcia** [comment]
Now, this has to be moved to the json schema descriptions. The specification will be generated automatically.
